spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/db_jobbies
      # O, si necesitas autenticación:
      # uri: mongodb://usuario:contraseña@localhost:27017/tu_base_de_datos
      # O, con propiedades separadas:
      # host: localhost
      # port: 27017
      # database: tu_base_de_datos
      # username: usuario
      # password: contraseña
security:
   jwt:
     key-secret: "3a9f6c4b2d1e8b7a5c3d1f9e7b6a4d3c2e1f0b9a8d7c6f5e4b3a2d1c0f9e8d7"